### ISSUE TITLE
Incorrect name shown for some entities?

### ISSUE THREAD

**Issue by fredrikbaberg** [alanfischer/hassiq#23]
Just discovered this widget for my Vivoactive 3 (happy to see it already existed, so I didn't have to try to write my own).

When creating a group with entities to show on my device I noticed some entities does not show the friendly name. I thought it was worse than it actually is at first, had to give it some time to display friendly names first.

The following domains I've discovered does not seem to show friendly name:
- automation
- binary_sensor
- device_tracker
- group (default ones, such as group.all_lights)
- utility_meter
- zone

The following domains shows friendly name, at least after some initial loading time:
- alarm_control_panel
- binary_sensor
- fan
- group (custom groups, not default ones)
- input_boolean
- input_number
- light
- media_player
- person
- scene
- script
- sensor
- sensor
- sun
- switch
- weather (tried with Dark Sky)

**Comment by alanfischer** [comment]
@fredrikbaberg  Sorry for the late response.  I am unable to reproduce this locally.  What version of home assistant are you running?  Do you have a simple home assistant configuration file you can share that reproduces this in HassIQ?

**Comment by fredrikbaberg** [comment]
Sorry for the late reply, it seems I'm not receiving notifications from GitHub.
I just tried with "group.all_lights", where the displayed name is "group.all_lights" instead of the friendly name "all lights". Same thing for group.all_automations.

I'm now on HassIO 0.98.5.

I'm using the following in `groups.yaml` to test, where `testgroup` started working after some trials but the others do not:
```
hassiq:
  name: HassIQ
  entities:
    - group.all_lights
    - group.all_automations
    - zone.home
    - group.testgroup

testgroup:
  name: MyTestGroup
  entities:
    - sun.sun
```
