### ISSUE TITLE
Status 404

### ISSUE THREAD

**Issue by ihard** [alanfischer/hassiq#28]
Hi, i check HassIQ 1.0.10 with Home Assistance 0.104.3 on Garmin 945
After login i have Status: 404 :(
Check with login/password and long time token - error same - Status: 404

**Comment by alanfischer** [comment]
A 404 would indicate the group you have setup in HassIQ is not found in your Home Assistant.  What group name do you have in HassIQ?

**Comment by ihard** [comment]
I edit groups.yaml to
```
default_view:
  name: Home
  view: yes
  entities:
    - group.home

home:
  name: home
  entities:
    - sensor.battery_level_2
```
and restart HA

in confg HassIQ set group.default_view
now i get 
`Status: -104`

Can you show some working configuration file for verification?
