### ISSUE TITLE
add support for climate

### ISSUE THREAD

**Issue by PawelTroka** [alanfischer/hassiq#34]
this one is a bit more difficult, depending on actual HVAC device we may need off, cool and heat. Maybe it could be configurable which device is on/off for cool/off and which is on/off for heat/off?

**Comment by niloc132** [comment]
I've hacked in a simple control for this by creating template switches and adding them to the group that is visible on my watch.

Example:
```
switch:
        - platform: template
          switches:
                  house_temp_up:
                          value_template: "{{ False == is_state_attr('climate.my_ecobee3', 'temperature', 67) }}"
                          turn_on:
                                  service: climate.set_temperature
                                  data:
                                          entity_id: climate.my_ecobee3
                                          temperature: 68
                          turn_off: # Puts the ecobee back in current program state
                                  service: climate.set_preset_mode
                                  data:
                                          entity_id: climate.my_ecobee3
                                          preset_mode: "{{ state_attr('climate.my_ecobee3', 'climate_mode') }}"
```

Very dumb sample, as it assumes that the default is 67, and pushes it only up to 68 degrees, but might be an inspiration for how you could achieve something similar. 

Main downside is that it is hard to get feedback other than on/off - but if you list all devices as on/off, that could be sufficient?
